"use strict";

/*****************

Random keyword generation
for question text and image files

******************/

let $animals = [
      "aardvark",
      "alligator",
      "alpaca",
      "antelope",
      "ape",
      "armadillo",
      "baboon",
      "badger",
      "bat",
      "bear",
      "beaver",
      "bison",
      "boar",
      "buffalo",
      "bull",
      "camel",
      "canary",
      "capybara",
      "cat",
      "chameleon",
      "cheetah",
      "chimpanzee",
      "chinchilla",
      "chipmunk",
      "cougar",
      "cow",
      "coyote",
      "crocodile",
      "crow",
      "deer",
      "dingo",
      "dog",
      "donkey",
      "dromedary",
      "elephant",
      "elk",
      "ewe",
      "ferret",
      "finch",
      "fish",
      "fox",
      "frog",
      "gazelle",
      "gila monster",
      "giraffe",
      "gnu",
      "goat",
      "gopher",
      "gorilla",
      "grizzly bear",
      "ground hog",
      "guinea pig",
      "hamster",
      "hedgehog",
      "hippopotamus",
      "hog",
      "horse",
      "hyena",
      "ibex",
      "iguana",
      "impala",
      "jackal",
      "jaguar",
      "kangaroo",
      "koala",
      "lamb",
      "lemur",
      "leopard",
      "lion",
      "lizard",
      "llama",
      "lynx",
      "mandrill",
      "marmoset",
      "mink",
      "mole",
      "mongoose",
      "monkey",
      "moose",
      "mountain goat",
      "mouse",
      "mule",
      "muskrat",
      "mustang",
      "mynah bird",
      "newt",
      "ocelot",
      "opossum",
      "orangutan",
      "oryx",
      "otter",
      "ox",
      "panda",
      "panther",
      "parakeet",
      "parrot",
      "pig",
      "platypus",
      "polar bear",
      "porcupine",
      "porpoise",
      "prairie dog",
      "puma",
      "rabbit",
      "raccoon",
      "ram",
      "rat",
      "reindeer",
      "reptile",
      "rhinoceros",
      "salamander",
      "seal",
      "sheep",
      "shrew",
      "silver fox",
      "skunk",
      "sloth",
      "snake",
      "squirrel",
      "tapir",
      "tiger",
      "toad",
      "turtle",
      "walrus",
      "warthog",
      "weasel",
      "whale",
      "wildcat",
      "wolf",
      "wolverine",
      "wombat",
      "woodchuck",
      "yak",
      "zebra"
    ]

let $mythicalCreatures =  [
      "angel",
      "brownie",
//      "bugbear",
      "centaur",
      "chimera",
//      "chupacabra",
//      "cockatrice",
      "cyclops",
      "demon",
//      "djinn",
      "dragon",
//      "draugr",
      "dryad",
      "dwarf",
      "elemental",
      "elf",
      "fairy",
      "faun",
//      "frost giant",
      "gargoyle",
      "genie",
//      "ghast",
      "ghost",
      "ghoul",
      "giant",
      "gnome",
      "goblin",
      "golem",
      "gorgon",
      "gremlin",
      "griffon",
//      "hag",
      "harpy",
      "hippogriff",
      "hobgoblin",
//      "homonculus",
      "hydra",
      "imp",
      "incubus",
//      "kappa",
//      "kobold",
//      "kraken",
//      "lamassu",
      "leprechaun",
//      "lich",
//      "manticore",
      "mermaid",
      "merman",
      "minotaur",
      "mummy",
//      "naga",
//      "nix",
      "nymph",
      "ogre",
//      "oni",
      "orc",
      "pegasus",
      "phoenix",
      "pixie",
      "poltergeist",
//      "roc",
      "sasquatch",
      "satyr",
//      "selkie",
      "siren",
      "spectre",
      "sphinx",
      "sprite",
      "succubus",
//      "sylph",
      "thunderbird",
      "troll",
      "unicorn",
      "vampire",
      "valkyrie",
      "warg",
//      "wendigo",
      "werewolf",
//      "wight",
      "witch",
      "wraith",
//      "wyvern",
      "yeti",
      "zombie"
    ]

let $vegetables = [
    "acorn squash",
    "alfalfa sprout",
    "amaranth",
    "anise",
    "artichoke",
    "arugula",
    "asparagus",
    "aubergine",
    "azuki bean",
//    "banana squash",
    "basil",
    "bean sprout",
    "beet",
//    "black bean",
//    "black-eyed pea",
    "bok choy",
//    "borlotti bean",
    "broad beans",
    "broccoflower",
    "broccoli",
//    "brussels sprout",
//    "butternut squash",
    "cabbage",
    "calabrese",
    "caraway",
    "carrot",
    "cauliflower",
//    "cayenne pepper",
    "celeriac",
    "celery",
    "chamomile",
    "chard",
    "chayote",
    "chickpea",
    "chives",
    "cilantro",
//    "collard green",
    "corn",
//    "corn salad",
    "courgette",
    "cucumber",
    "daikon",
    "delicata",
    "dill",
    "eggplant",
    "endive",
    "fennel",
    "fiddlehead",
    "frisee",
    "garlic",
//    "gem squash",
    "ginger",
    "green bean",
    "green pepper",
    "habanero",
//    "herbs and spice",
    "horseradish",
//    "hubbard squash",
    "jalapeno",
//    "jerusalem artichoke",
//    "jicama",
    "kale",
//    "kidney bean",
    "kohlrabi",
    "lavender",
    "leek ",
    "legume",
//    "lemon grass",
    "lentils",
    "lettuce",
//    "lima bean",
    "mamey",
//    "mangetout",
    "marjoram",
    "mung bean",
    "mushroom",
    "mustard green",
    "navy bean",
//    "new zealand spinach",
    "nopale",
    "okra",
    "onion",
    "oregano",
    "paprika",
    "parsley",
    "parsnip",
//    "patty pan",
    "pea",
//    "pinto bean",
    "potato",
    "pumpkin",
    "radicchio",
    "radish",
    "rhubarb",
    "rosemary",
//    "runner bean",
    "rutabaga",
    "sage",
    "scallion",
    "shallot",
    "skirret",
    "snap pea",
    "soy bean",
//    "spaghetti squash",
    "spinach",
    "squash ",
//    "sweet potato",
//    "tabasco pepper",
    "taro",
//    "tat soi",
    "thyme",
    "topinambur",
    "tubers",
    "turnip",
    "wasabi",
//    "water chestnut",
    "watercress",
//    "white radish",
    "yam",
    "zucchini"
]

let $positions = [
  "accountant",
  "partner"
]

let $bodyParts = [
  "ankle",
  "arm",
  "back",
  "belly",
  "bottom",
  "breast",
  "buttocks",
  "calf",
  "cheek",
  "chin",
  "ear",
  "elbow",
  "eye",
  "eyebrow",
  "eyelash",
  "finger",
  "fist",
  "foot",
  "forearm",
  "forehead",
  "hair",
  "hand",
  "head",
  "hip",
  "knee",
  "leg",
  "lip",
//  "lower leg",
  "mouth",
  "neck",
  "nose",
  "nostril",
  "shoulder",
  "thigh",
  "thumb",
  "toe",
  "tongue",
  "tooth",
//  "upper arm",
  "waist",
  "wrist"
]

let $cuteKaomoji = [
  "（´・｀ ）♡",
  "(✿ ♥‿♥)",
  "(♥ω♥*)",
  "(∿°○°)∿ ︵ ǝʌol",
  "(๑°꒵°๑)･*♡",
  "♡´･ᴗ･`♡",
  "(´•ω•｀♥)",
  "(*´c_,｀*)",
  "(●´Д`●)",
  "(つω`●）",
  "(●⌒ｖ⌒●)",
  "｡◕‿◕｡",
  "(◕‿◕✿)",
  "(◡‿◡✿)",
  "(✿◠‿◠)",
  "(ㆁᴗㆁ✿)",
  "(ᅌᴗᅌ* )",
  "(๑╹っ╹๑)",
  "°˖✧◝(⁰▿⁰)◜✧˖°",
  "(•　ω　•)",
  "(灬╹ω╹灬)",
  "٩(๑❛ᴗ❛๑)۶",
  "(◍•ᴗ•◍)",
  "╰(*´︶`*)╯",
  "✿*,(*´◕ω◕`*)+✿.*",
  "(✾♛‿♛)ノ*♡*",
  "(◔ᴥ◔)",
  "ﾟ･✿ヾ╲(｡◕‿◕｡)╱✿･ﾟ",
  "≧◠◡◠≦",
  "ʕ•ᴥ•ʔ"
]

let $emoji = [
  "🀄",
  "🃏",
  "🅰",
  "🅱",
  "🅾",
  "🅿",
  "🆎",
  "🆑",
  "🆒",
  "🆓",
  "🆔",
  "🆕",
  "🆖",
  "🆗",
  "🆘",
  "🆙",
  "🆚",
  "🇦",
  "🇧",
  "🇨",
  "🇩",
  "🇪",
  "🇫",
  "🇬",
  "🇭",
  "🇮",
  "🇯",
  "🇰",
  "🇱",
  "🇲",
  "🇳",
  "🇴",
  "🇵",
  "🇶",
  "🇷",
  "🇸",
  "🇹",
  "🇺",
  "🇻",
  "🇼",
  "🇽",
  "🇾",
  "🇿",
  "🈁",
  "🈂",
  "🈚",
  "🈯",
  "🈲",
  "🈳",
  "🈴",
  "🈵",
  "🈶",
  "🈷",
  "🈸",
  "🈹",
  "🈺",
  "🉐",
  "🉑",
  "🌀",
  "🌁",
  "🌂",
  "🌃",
  "🌄",
  "🌅",
  "🌆",
  "🌇",
  "🌈",
  "🌉",
  "🌊",
  "🌋",
  "🌌",
  "🌍",
  "🌎",
  "🌏",
  "🌐",
  "🌑",
  "🌒",
  "🌓",
  "🌔",
  "🌕",
  "🌖",
  "🌗",
  "🌘",
  "🌙",
  "🌚",
  "🌛",
  "🌜",
  "🌝",
  "🌞",
  "🌟",
  "🌠",
  "🌰",
  "🌱",
  "🌲",
  "🌳",
  "🌴",
  "🌵",
  "🌷",
  "🌸",
  "🌹",
  "🌺",
  "🌻",
  "🌼",
  "🌽",
  "🌾",
  "🌿",
  "🍀",
  "🍁",
  "🍂",
  "🍃",
  "🍄",
  "🍅",
  "🍆",
  "🍇",
  "🍈",
  "🍉",
  "🍊",
  "🍋",
  "🍌",
  "🍍",
  "🍎",
  "🍏",
  "🍐",
  "🍑",
  "🍒",
  "🍓",
  "🍔",
  "🍕",
  "🍖",
  "🍗",
  "🍘",
  "🍙",
  "🍚",
  "🍛",
  "🍜",
  "🍝",
  "🍞",
  "🍟",
  "🍠",
  "🍡",
  "🍢",
  "🍣",
  "🍤",
  "🍥",
  "🍦",
  "🍧",
  "🍨",
  "🍩",
  "🍪",
  "🍫",
  "🍬",
  "🍭",
  "🍮",
  "🍯",
  "🍰",
  "🍱",
  "🍲",
  "🍳",
  "🍴",
  "🍵",
  "🍶",
  "🍷",
  "🍸",
  "🍹",
  "🍺",
  "🍻",
  "🍼",
  "🎀",
  "🎁",
  "🎂",
  "🎃",
  "🎄",
  "🎅",
  "🎆",
  "🎇",
  "🎈",
  "🎉",
  "🎊",
  "🎋",
  "🎌",
  "🎍",
  "🎎",
  "🎏",
  "🎐",
  "🎑",
  "🎒",
  "🎓",
  "🎠",
  "🎡",
  "🎢",
  "🎣",
  "🎤",
  "🎥",
  "🎦",
  "🎧",
  "🎨",
  "🎩",
  "🎪",
  "🎫",
  "🎬",
  "🎭",
  "🎮",
  "🎯",
  "🎰",
  "🎱",
  "🎲",
  "🎳",
  "🎴",
  "🎵",
  "🎶",
  "🎷",
  "🎸",
  "🎹",
  "🎺",
  "🎻",
  "🎼",
  "🎽",
  "🎾",
  "🎿",
  "🏀",
  "🏁",
  "🏂",
  "🏃",
  "🏄",
  "🏆",
  "🏇",
  "🏈",
  "🏉",
  "🏊",
  "🏠",
  "🏡",
  "🏢",
  "🏣",
  "🏤",
  "🏥",
  "🏦",
  "🏧",
  "🏨",
  "🏩",
  "🏪",
  "🏫",
  "🏬",
  "🏭",
  "🏮",
  "🏯",
  "🏰",
  "🐀",
  "🐁",
  "🐂",
  "🐃",
  "🐄",
  "🐅",
  "🐆",
  "🐇",
  "🐈",
  "🐉",
  "🐊",
  "🐋",
  "🐌",
  "🐍",
  "🐎",
  "🐏",
  "🐐",
  "🐑",
  "🐒",
  "🐓",
  "🐔",
  "🐕",
  "🐖",
  "🐗",
  "🐘",
  "🐙",
  "🐚",
  "🐛",
  "🐜",
  "🐝",
  "🐞",
  "🐟",
  "🐠",
  "🐡",
  "🐢",
  "🐣",
  "🐤",
  "🐥",
  "🐦",
  "🐧",
  "🐨",
  "🐩",
  "🐪",
  "🐫",
  "🐬",
  "🐭",
  "🐮",
  "🐯",
  "🐰",
  "🐱",
  "🐲",
  "🐳",
  "🐴",
  "🐵",
  "🐶",
  "🐷",
  "🐸",
  "🐹",
  "🐺",
  "🐻",
  "🐼",
  "🐽",
  "🐾",
  "👀",
  "👂",
  "👃",
  "👄",
  "👅",
  "👆",
  "👇",
  "👈",
  "👉",
  "👊",
  "👋",
  "👌",
  "👍",
  "👎",
  "👏",
  "👐",
  "👑",
  "👒",
  "👓",
  "👔",
  "👕",
  "👖",
  "👗",
  "👘",
  "👙",
  "👚",
  "👛",
  "👜",
  "👝",
  "👞",
  "👟",
  "👠",
  "👡",
  "👢",
  "👣",
  "👤",
  "👥",
  "👦",
  "👧",
  "👨",
  "👩",
  "👪",
  "👫",
  "👬",
  "👭",
  "👮",
  "👯",
  "👰",
  "👱",
  "👲",
  "👳",
  "👴",
  "👵",
  "👶",
  "👷",
  "👸",
  "👹",
  "👺",
  "👻",
  "👼",
  "👽",
  "👾",
  "👿",
  "💀",
  "💁",
  "💂",
  "💃",
  "💄",
  "💅",
  "💆",
  "💇",
  "💈",
  "💉",
  "💊",
  "💋",
  "💌",
  "💍",
  "💎",
  "💏",
  "💐",
  "💑",
  "💒",
  "💓",
  "💔",
  "💕",
  "💖",
  "💗",
  "💘",
  "💙",
  "💚",
  "💛",
  "💜",
  "💝",
  "💞",
  "💟",
  "💠",
  "💡",
  "💢",
  "💣",
  "💤",
  "💥",
  "💦",
  "💧",
  "💨",
  "💩",
  "💪",
  "💫",
  "💬",
  "💭",
  "💮",
  "💯",
  "💰",
  "💱",
  "💲",
  "💳",
  "💴",
  "💵",
  "💶",
  "💷",
  "💸",
  "💹",
  "💺",
  "💻",
  "💼",
  "💽",
  "💾",
  "💿",
  "📀",
  "📁",
  "📂",
  "📃",
  "📄",
  "📅",
  "📆",
  "📇",
  "📈",
  "📉",
  "📊",
  "📋",
  "📌",
  "📍",
  "📎",
  "📏",
  "📐",
  "📑",
  "📒",
  "📓",
  "📔",
  "📕",
  "📖",
  "📗",
  "📘",
  "📙",
  "📚",
  "📛",
  "📜",
  "📝",
  "📞",
  "📟",
  "📠",
  "📡",
  "📢",
  "📣",
  "📤",
  "📥",
  "📦",
  "📧",
  "📨",
  "📩",
  "📪",
  "📫",
  "📬",
  "📭",
  "📮",
  "📯",
  "📰",
  "📱",
  "📲",
  "📳",
  "📴",
  "📵",
  "📶",
  "📷",
  "📹",
  "📺",
  "📻",
  "📼",
  "🔀",
  "🔁",
  "🔂",
  "🔃",
  "🔄",
  "🔅",
  "🔆",
  "🔇",
  "🔈",
  "🔉",
  "🔊",
  "🔋",
  "🔌",
  "🔍",
  "🔎",
  "🔏",
  "🔐",
  "🔑",
  "🔒",
  "🔓",
  "🔔",
  "🔕",
  "🔖",
  "🔗",
  "🔘",
  "🔙",
  "🔚",
  "🔛",
  "🔜",
  "🔝",
  "🔞",
  "🔟",
  "🔠",
  "🔡",
  "🔢",
  "🔣",
  "🔤",
  "🔥",
  "🔦",
  "🔧",
  "🔨",
  "🔩",
  "🔪",
  "🔫",
  "🔬",
  "🔭",
  "🔮",
  "🔯",
  "🔰",
  "🔱",
  "🔲",
  "🔳",
  "🔴",
  "🔵",
  "🔶",
  "🔷",
  "🔸",
  "🔹",
  "🔺",
  "🔻",
  "🔼",
  "🔽",
  "🕐",
  "🕑",
  "🕒",
  "🕓",
  "🕔",
  "🕕",
  "🕖",
  "🕗",
  "🕘",
  "🕙",
  "🕚",
  "🕛",
  "🕜",
  "🕝",
  "🕞",
  "🕟",
  "🕠",
  "🕡",
  "🕢",
  "🕣",
  "🕤",
  "🕥",
  "🕦",
  "🕧",
  "🗻",
  "🗼",
  "🗽",
  "🗾",
  "🗿",
  "😀",
  "😁",
  "😂",
  "😃",
  "😄",
  "😅",
  "😆",
  "😇",
  "😈",
  "😉",
  "😊",
  "😋",
  "😌",
  "😍",
  "😎",
  "😏",
  "😐",
  "😑",
  "😒",
  "😓",
  "😔",
  "😕",
  "😖",
  "😗",
  "😘",
  "😙",
  "😚",
  "😛",
  "😜",
  "😝",
  "😞",
  "😟",
  "😠",
  "😡",
  "😢",
  "😣",
  "😤",
  "😥",
  "😦",
  "😧",
  "😨",
  "😩",
  "😪",
  "😫",
  "😬",
  "😭",
  "😮",
  "😯",
  "😰",
  "😱",
  "😲",
  "😳",
  "😴",
  "😵",
  "😶",
  "😷",
  "😸",
  "😹",
  "😺",
  "😻",
  "😼",
  "😽",
  "😾",
  "😿",
  "🙀",
  "🙁",
  "🙂",
  "🙅",
  "🙆",
  "🙇",
  "🙈",
  "🙉",
  "🙊",
  "🙋",
  "🙌",
  "🙍",
  "🙎",
  "🙏",
  "🚀",
  "🚁",
  "🚂",
  "🚃",
  "🚄",
  "🚅",
  "🚆",
  "🚇",
  "🚈",
  "🚉",
  "🚊",
  "🚋",
  "🚌",
  "🚍",
  "🚎",
  "🚏",
  "🚐",
  "🚑",
  "🚒",
  "🚓",
  "🚔",
  "🚕",
  "🚖",
  "🚗",
  "🚘",
  "🚙",
  "🚚",
  "🚛",
  "🚜",
  "🚝",
  "🚞",
  "🚟",
  "🚠",
  "🚡",
  "🚢",
  "🚣",
  "🚤",
  "🚥",
  "🚦",
  "🚧",
  "🚨",
  "🚩",
  "🚪",
  "🚫",
  "🚬",
  "🚭",
  "🚮",
  "🚯",
  "🚰",
  "🚱",
  "🚲",
  "🚳",
  "🚴",
  "🚵",
  "🚶",
  "🚷",
  "🚸",
  "🚹",
  "🚺",
  "🚻",
  "🚼",
  "🚽",
  "🚾",
  "🚿",
  "🛀",
  "🛁",
  "🛂",
  "🛃",
  "🛄",
  "🛅",
  "‼",
  "⁉",
  "™",
  "ℹ",
  "↔",
  "↕",
  "↖",
  "↗",
  "↘",
  "↙",
  "↩",
  "↪",
  "#",
  "⌚",
  "⌛",
  "⏩",
  "⏪",
  "⏫",
  "⏬",
  "⏰",
  "⏳",
  "Ⓜ",
  "▪",
  "▫",
  "▶",
  "◀",
  "◻",
  "◼",
  "◽",
  "◾",
  "☀",
  "☁",
  "☎",
  "☑",
  "☔",
  "☕",
  "☝",
  "☺",
  "♈",
  "♉",
  "♊",
  "♋",
  "♌",
  "♍",
  "♎",
  "♏",
  "♐",
  "♑",
  "♒",
  "♓",
  "♠",
  "♣",
  "♥",
  "♦",
  "♨",
  "♻",
  "♿",
  "⚓",
  "⚠",
  "⚡",
  "⚪",
  "⚫",
  "⚽",
  "⚾",
  "⛄",
  "⛅",
  "⛎",
  "⛔",
  "⛪",
  "⛲",
  "⛳",
  "⛵",
  "⛺",
  "⛽",
  "✂",
  "✅",
  "✈",
  "✉",
  "✊",
  "✋",
  "✌",
  "✏",
  "✒",
  "✔",
  "✖",
  "✨",
  "✳",
  "✴",
  "❄",
  "❇",
  "❌",
  "❎",
  "❓",
  "❔",
  "❕",
  "❗",
  "❤",
  "➕",
  "➖",
  "➗",
  "➡",
  "➰",
  "➿",
  "⤴",
  "⤵",
  "⬅",
  "⬆",
  "⬇",
  "⬛",
  "⬜",
  "⭐",
  "⭕",
  "0",
  "〰",
  "〽",
  "1",
  "2",
  "㊗",
  "㊙",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "©",
  "®",
  ""
]

let $adjectives = [
  "Aristotelian",
  "Arthurian",
  "Bohemian",
  "Brethren",
  "Mosaic",
  "Oceanic",
  "Proctor",
  "Terran",
  "Tudor",
  "abroad",
  "absorbing",
  "abstract",
  "academic",
  "accelerated",
  "accented",
  "accountant",
  "acquainted",
  "acute",
  "addicting",
  "addictive",
  "adjustable",
  "admired",
  "adult",
  "adverse",
  "advised",
  "aerosol",
  "afraid",
  "aggravated",
  "aggressive",
  "agreeable",
  "alienate",
  "aligned",
  "all-round",
  "alleged",
  "almond",
  "alright",
  "altruistic",
  "ambient",
  "ambivalent",
  "amiable",
  "amino",
  "amorphous",
  "amused",
  "anatomical",
  "ancestral",
  "angelic",
  "angrier",
  "answerable",
  "antiquarian",
  "antiretroviral",
  "appellate",
  "applicable",
  "apportioned",
  "approachable",
  "appropriated",
  "archer",
  "aroused",
  "arrested",
  "assertive",
  "assigned",
  "athletic",
  "atrocious",
  "attained",
  "authoritarian",
  "autobiographical",
  "avaricious",
  "avocado",
  "awake",
  "awsome",
  "backstage",
  "backwoods",
  "balding",
  "bandaged",
  "banded",
  "banned",
  "barreled",
  "battle",
  "beaten",
  "begotten",
  "beguiled",
  "bellied",
  "belted",
  "beneficent",
  "besieged",
  "betting",
  "big-money",
  "biggest",
  "biochemical",
  "bipolar",
  "blackened",
  "blame",
  "blessed",
  "blindfolded",
  "bloat",
  "blocked",
  "blooded",
  "blue-collar",
  "blushing",
  "boastful",
  "bolder",
  "bolstered",
  "bonnie",
  "bored",
  "boundary",
  "bounded",
  "bounding",
  "branched",
  "brawling",
  "brazen",
  "breeding",
  "bridged",
  "brimming",
  "brimstone",
  "broadest",
  "broiled",
  "broker",
  "bronze",
  "bruising",
  "buffy",
  "bullied",
  "bungling",
  "burial",
  "buttery",
  "candied",
  "canonical",
  "cantankerous",
  "cardinal",
  "carefree",
  "caretaker",
  "casual",
  "cathartic",
  "causal",
  "chapel",
  "characterized",
  "charcoal",
  "cheeky",
  "cherished",
  "chipotle",
  "chirping",
  "chivalrous",
  "circumstantial",
  "civic",
  "civil",
  "civilised",
  "clanking",
  "clapping",
  "claptrap",
  "classless",
  "cleansed",
  "cleric",
  "cloistered",
  "codified",
  "colloquial",
  "colour",
  "combat",
  "combined",
  "comely",
  "commissioned",
  "commonplace",
  "commuter",
  "commuting",
  "comparable",
  "complementary",
  "compromising",
  "conceding",
  "concentrated",
  "conceptual",
  "conditioned",
  "confederate",
  "confident",
  "confidential",
  "confining",
  "confuse",
  "congressional",
  "consequential",
  "conservative",
  "constituent",
  "contaminated",
  "contemporaneous",
  "contraceptive",
  "convertible",
  "convex",
  "cooked",
  "coronary",
  "corporatist",
  "correlated",
  "corroborated",
  "cosmic",
  "cover",
  "crash",
  "crypto",
  "culminate",
  "cushioned",
  "dandy",
  "dashing",
  "dazzled",
  "decreased",
  "decrepit",
  "dedicated",
  "defaced",
  "defective",
  "defenseless",
  "deluded",
  "deodorant",
  "departed",
  "depress",
  "designing",
  "despairing",
  "destitute",
  "detective",
  "determined",
  "devastating",
  "deviant",
  "devilish",
  "devoted",
  "diagonal",
  "dictated",
  "didactic",
  "differentiated",
  "diffused",
  "dirtier",
  "disabling",
  "disconnected",
  "discovered",
  "disdainful",
  "diseased",
  "disfigured",
  "disheartened",
  "disheveled",
  "disillusioned",
  "disparate",
  "dissident",
  "doable",
  "doctrinal",
  "doing",
  "dotted",
  "double-blind",
  "downbeat",
  "dozen",
  "draining",
  "draught",
  "dread",
  "dried",
  "dropped",
  "dulled",
  "duplicate",
  "eaten",
  "echoing",
  "economical",
  "elaborated",
  "elastic",
  "elective",
  "electoral",
  "elven",
  "embryo",
  "emerald",
  "emergency",
  "emissary",
  "emotional",
  "employed",
  "enamel",
  "encased",
  "encrusted",
  "endangered",
  "engraved",
  "engrossing",
  "enlarged",
  "enlisted",
  "enlivened",
  "ensconced",
  "entangled",
  "enthralling",
  "entire",
  "envious",
  "eradicated",
  "eroded",
  "esoteric",
  "essential",
  "evaporated",
  "ever-present",
  "evergreen",
  "everlasting",
  "exacting",
  "exasperated",
  "excess",
  "exciting",
  "executable",
  "existent",
  "exonerated",
  "exorbitant",
  "exponential",
  "export",
  "extraordinary",
  "exultant",
  "exulting",
  "facsimile",
  "fading",
  "fainter",
  "faith-based",
  "fallacious",
  "faltering",
  "famous",
  "fancier",
  "fast-growing",
  "fated",
  "favourable",
  "fearless",
  "feathered",
  "fellow",
  "fermented",
  "ferocious",
  "fiddling",
  "filling",
  "firmer",
  "fitted",
  "flammable",
  "flawed",
  "fledgling",
  "fleshy",
  "flexible",
  "flickering",
  "floral",
  "flowering",
  "flowing",
  "foggy",
  "folic",
  "foolhardy",
  "foolish",
  "footy",
  "forehand",
  "forked",
  "formative",
  "formulaic",
  "foul-mouthed",
  "fractional",
  "fragrant",
  "fraudulent",
  "freakish",
  "freckled",
  "freelance",
  "freight",
  "fresh",
  "fretted",
  "frugal",
  "fulfilling",
  "fuming",
  "funded",
  "funny",
  "garbled",
  "gathered",
  "geologic",
  "geometric",
  "gibberish",
  "gilded",
  "ginger",
  "glare",
  "glaring",
  "gleaming",
  "glorified",
  "glorious",
  "goalless",
  "gold-plated",
  "goody",
  "grammatical",
  "grande",
  "grateful",
  "gratuitous",
  "graven",
  "greener",
  "grinding",
  "grizzly",
  "groaning",
  "grudging",
  "guaranteed",
  "gusty",
  "half-breed",
  "hand-held",
  "handheld",
  "hands-off",
  "hard-pressed",
  "harlot",
  "healing",
  "healthier",
  "healthiest",
  "heart",
  "heart-shaped",
  "heathen",
  "hedonistic",
  "heralded",
  "herbal",
  "high-density",
  "high-performance",
  "high-res",
  "high-yield",
  "hissy",
  "hitless",
  "holiness",
  "homesick",
  "honorable",
  "hooded",
  "hopeless",
  "horrendous",
  "horrible",
  "hot-button",
  "huddled",
  "human",
  "humbling",
  "humid",
  "humiliating",
  "hypnotized",
  "idealistic",
  "idiosyncratic",
  "ignited",
  "illustrated",
  "illustrative",
  "imitated",
  "immense",
  "immersive",
  "immigrant",
  "immoral",
  "impassive",
  "impressionable",
  "improbable",
  "impulsive",
  "in-between",
  "in-flight",
  "inattentive",
  "inbound",
  "inbounds",
  "incalculable",
  "incomprehensible",
  "indefatigable",
  "indigo",
  "indiscriminate",
  "indomitable",
  "inert",
  "inflate",
  "inform",
  "inheriting",
  "injured",
  "injurious",
  "inking",
  "inoffensive",
  "insane",
  "insensible",
  "insidious",
  "insincere",
  "insistent",
  "insolent",
  "insufferable",
  "intemperate",
  "interdependent",
  "interesting",
  "interfering",
  "intern",
  "interpreted",
  "intersecting",
  "intolerable",
  "intolerant",
  "intuitive",
  "irresolute",
  "irritate",
  "jealous",
  "jerking",
  "joining",
  "joint",
  "journalistic",
  "joyful",
  "keyed",
  "knowing",
  "lacklustre",
  "laden",
  "lagging",
  "lamented",
  "laughable",
  "layered",
  "leather",
  "leathern",
  "leery",
  "left-footed",
  "legible",
  "leisure",
  "lessening",
  "liberating",
  "life-size",
  "lifted",
  "lightest",
  "limitless",
  "listening",
  "literary",
  "liver",
  "livid",
  "lobster",
  "locked",
  "long-held",
  "long-lasting",
  "long-running",
  "long-suffering",
  "loudest",
  "loveliest",
  "low-budget",
  "low-carb",
  "lowering",
  "lucid",
  "luckless",
  "lusty",
  "luxurious",
  "magazine",
  "maniac",
  "manmade",
  "maroon",
  "mastered",
  "mated",
  "material",
  "materialistic",
  "meaningful",
  "measuring",
  "mediaeval",
  "medical",
  "meditated",
  "medley",
  "melodic",
  "memorable",
  "memorial",
  "metabolic",
  "metallic",
  "metallurgical",
  "metering",
  "midair",
  "midterm",
  "midway",
  "mighty",
  "migrating",
  "mind-blowing",
  "mind-boggling",
  "minor",
  "mirrored",
  "misguided",
  "misshapen",
  "mitigated",
  "mixed",
  "modernized",
  "molecular",
  "monarch",
  "monastic",
  "morbid",
  "motley",
  "motorized",
  "mounted",
  "multi-million",
  "multidisciplinary",
  "muscled",
  "muscular",
  "muted",
  "mysterious",
  "mythic",
  "nail-biting",
  "natural",
  "nauseous",
  "negative",
  "networked",
  "neurological",
  "neutered",
  "newest",
  "night",
  "nitrous",
  "no-fly",
  "noncommercial",
  "nonsense",
  "north",
  "nuanced",
  "occurring",
  "offensive",
  "oldest",
  "oncoming",
  "one-eyed",
  "one-year",
  "onstage",
  "onward",
  "opaque",
  "open-ended",
  "operating",
  "opportunist",
  "opposing",
  "opt-in",
  "ordinate",
  "outdone",
  "outlaw",
  "outsized",
  "overboard",
  "overheated",
  "oversize",
  "overworked",
  "oyster",
  "paced",
  "panting",
  "paralyzed",
  "paramount",
  "parental",
  "parted",
  "partisan",
  "passive",
  "pastel",
  "patriot",
  "peacekeeping",
  "pedestrian",
  "peevish",
  "penal",
  "penned",
  "pensive",
  "perceptual",
  "perky",
  "permissible",
  "pernicious",
  "perpetuate",
  "perplexed",
  "pervasive",
  "petrochemical",
  "philosophical",
  "picturesque",
  "pillaged",
  "piped",
  "piquant",
  "pitching",
  "plausible",
  "pliable",
  "plumb",
  "politician",
  "polygamous",
  "poorest",
  "portmanteau",
  "posed",
  "positive",
  "possible",
  "postpartum",
  "prank",
  "pre-emptive",
  "precocious",
  "predicted",
  "premium",
  "preparatory",
  "prerequisite",
  "prescient",
  "preserved",
  "presidential",
  "pressed",
  "pressurized",
  "presumed",
  "prewar",
  "priced",
  "pricier",
  "primal",
  "primer",
  "primetime",
  "printed",
  "private",
  "problem",
  "procedural",
  "process",
  "prodigious",
  "professional",
  "programmed",
  "progressive",
  "prolific",
  "promising",
  "promulgated",
  "pronged",
  "proportionate",
  "protracted",
  "pulled",
  "pulsed",
  "purgatory",
  "quick",
  "rapid-fire",
  "raunchy",
  "razed",
  "reactive",
  "readable",
  "realizing",
  "recognised",
  "recovering",
  "recurrent",
  "recycled",
  "redeemable",
  "reflecting",
  "regal",
  "registering",
  "reliable",
  "reminiscent",
  "remorseless",
  "removable",
  "renewable",
  "repeating",
  "repellent",
  "reserve",
  "resigned",
  "respectful",
  "rested",
  "restrict",
  "resultant",
  "retaliatory",
  "retiring",
  "revelatory",
  "reverend",
  "reversing",
  "revolving",
  "ridiculous",
  "right-hand",
  "ringed",
  "risque",
  "robust",
  "roomful",
  "rotating",
  "roused",
  "rubber",
  "run-down",
  "running",
  "runtime",
  "rustling",
  "safest",
  "salient",
  "sanctioned",
  "saute",
  "saved",
  "scandalized",
  "scarlet",
  "scattering",
  "sceptical",
  "scheming",
  "scoundrel",
  "scratched",
  "scratchy",
  "scrolled",
  "seated",
  "second-best",
  "segregated",
  "self-taught",
  "semiautomatic",
  "senior",
  "sensed",
  "sentient",
  "sexier",
  "shadowy",
  "shaken",
  "shaker",
  "shameless",
  "shaped",
  "shiny",
  "shipped",
  "shivering",
  "shoestring",
  "short",
  "short-lived",
  "signed",
  "simplest",
  "simplistic",
  "sizable",
  "skeleton",
  "skinny",
  "skirting",
  "skyrocketed",
  "slamming",
  "slanting",
  "slapstick",
  "sleek",
  "sleepless",
  "sleepy",
  "slender",
  "slimmer",
  "smacking",
  "smokeless",
  "smothered",
  "smouldering",
  "snuff",
  "socialized",
  "solid-state",
  "sometime",
  "sought",
  "spanking",
  "sparing",
  "spattered",
  "specialized",
  "specific",
  "speedy",
  "spherical",
  "spiky",
  "spineless",
  "sprung",
  "squint",
  "stainless",
  "standing",
  "starlight",
  "startled",
  "stately",
  "statewide",
  "stereoscopic",
  "sticky",
  "stimulant",
  "stinky",
  "stoked",
  "stolen",
  "storied",
  "strained",
  "strapping",
  "strengthened",
  "stubborn",
  "stylized",
  "suave",
  "subjective",
  "subjugated",
  "subordinate",
  "succeeding",
  "suffering",
  "summary",
  "sunset",
  "sunshine",
  "supernatural",
  "supervisory",
  "supply-side",
  "surrogate",
  "suspended",
  "suspenseful",
  "swarthy",
  "sweating",
  "sweeping",
  "swinging",
  "swooning",
  "sympathize",
  "synchronized",
  "synonymous",
  "synthetic",
  "tailed",
  "tallest",
  "tangible",
  "tanked",
  "tarry",
  "technical",
  "tectonic",
  "telepathic",
  "tenderest",
  "territorial",
  "testimonial",
  "theistic",
  "thicker",
  "threatening",
  "tight-lipped",
  "timed",
  "timely",
  "timid",
  "torrent",
  "totalled",
  "tougher",
  "traditional",
  "transformed",
  "trapped",
  "traveled",
  "traverse",
  "treated",
  "trial",
  "trunk",
  "trusting",
  "trying",
  "twisted",
  "two-lane",
  "tyrannical",
  "unaided",
  "unassisted",
  "unassuming",
  "unattractive",
  "uncapped",
  "uncomfortable",
  "uncontrolled",
  "uncooked",
  "uncooperative",
  "underground",
  "undersea",
  "undisturbed",
  "unearthly",
  "uneasy",
  "unequal",
  "unfazed",
  "unfinished",
  "unforeseen",
  "unforgivable",
  "unidentified",
  "unimaginative",
  "uninspired",
  "unintended",
  "uninvited",
  "universal",
  "unmasked",
  "unorthodox",
  "unparalleled",
  "unpleasant",
  "unprincipled",
  "unread",
  "unreasonable",
  "unregulated",
  "unreliable",
  "unremitting",
  "unsafe",
  "unsanitary",
  "unsealed",
  "unsuccessful",
  "unsupervised",
  "untimely",
  "unwary",
  "unwrapped",
  "uppity",
  "upstart",
  "useless",
  "utter",
  "valiant",
  "valid",
  "valued",
  "vanilla",
  "vaulting",
  "vaunted",
  "veering",
  "vegetative",
  "vented",
  "verbal",
  "verifying",
  "veritable",
  "versed",
  "vinyl",
  "virgin",
  "visceral",
  "visual",
  "voluptuous",
  "walk-on",
  "wanton",
  "warlike",
  "washed",
  "waterproof",
  "waved",
  "weakest",
  "well-bred",
  "well-chosen",
  "well-informed",
  "wetting",
  "wheeled",
  "whirlwind",
  "widen",
  "widening",
  "willful",
  "willing",
  "winnable",
  "winningest",
  "wireless",
  "wistful",
  "woeful",
  "wooded",
  "woodland",
  "wordless",
  "workable",
  "worldly",
  "worldwide",
  "worst-case",
  "worsted",
  "worthless"]

let $wisdom = [
  "A change is as good as a rest.",
  "A stitch in time saves nine.",
  "A throne is only a bench covered in purple velvet.",
  "A wise man shall hold his tongue till he sees his opportunity.",
  "Accidents will happen.",
  "All's well that ends well.",
  "Attack is the best means of defence.",
  "Charity begins at home.",
  "Different strokes for different folks.",
  "Do not in an instant what an age cannot recompense.",
  "Don't knock on death's door, ring the doorbell and run.",
  "Don't try to teach your grand-mother to suck eggs.",
  "Empty vessels make the most sound.",
  "Empty barrels make the most noise.",
  "Four eyes are better than two.",
  "He who fights and runs away, lives to fight another day.",
  "Innocent as a new born babe.",
  "It's an ill wind that blows no-one some good.",
  "It is better to stay silent and be thought a fool, than to open one's mouth and remove all doubt.",
  "Necessity is the mother of invention.",
  "No one can be caught in places he does not visit.",
  "No wise man ever wishes to be younger.",
  "Not in a month of Sundays.",
  "One mans junk is another man's treasure.",
  "Out of the frying pan into the fire.",
  "Show a clean pair of heels.",
  "Still waters run deep.",
  "The darkest hour is before the dawn.",
  "The wise shall understand.",
  "Those who don't learn from history are doomed to repeat it.",
  "Tomorrow is a new day.",
  "Two heads are better than one.",
  "You can't tell a book by its cover.",
  "Where observation is concerned, chance favours only the prepared mind.",
  "Where there's smoke there's fire.",
  "Wisdom is better than strength.",
  "Wisdom is neither inheritance nor a legacy.",
  "Wisdom is the wealth of the wise.",
  "Wise it is to comprehend the whole.",
  "You can't put an old head on young shoulders.",
  "You never know what you can do till you try."
]

let $affirmations = [
  "Life loves me!",
  "All is well in my world. Everything is working out for my highest good. Out of this situation only good will come. I am safe!",
  "It’s only a thought, and a thought can be changed.",
  "The point of power is always in the present moment.",
  "Every thought we think is creating our future.",
  "I am comfortable looking in the mirror, saying, \“I love you, I really love you.\”",
  "It is safe to look within.",
  "I forgive myself and set myself free.",
  "As I say yes to life, life says yes to me.",
  "I now go beyond other people’s fears and limitations.",
  "I am Divinely guided and protected at all times.",
  "I claim my power and move beyond all limitations.",
  "I trust the process of life.",
  "I am deeply fulfilled by all that I do.",
  "We are all family, and the planet is our home.",
  "As I forgive myself, it becomes easier to forgive others.",
  "I am willing to let go.",
  "Deep at the center of my being is an infinite well of love.",
  "I prosper wherever I turn.",
  "I welcome miracles into my life.",
  "Whatever I need to know is revealed to me at exactly the right time.",
  "I am loved, and I am at peace.",
  "My happy thoughts help create my healthy body.",
  "Life supports me in every possible way.",
  "My day begins and ends with gratitude.",
  "I listen with love to my body’s messages.",
  "The past is over.",
  "Only good can come to me.",
  "I am beautiful, and everybody loves me.",
  "Everyone I encounter today has my best interests at heart.",
  "I always work with and for wonderful people. I love my job.",
  "Filling my mind with pleasant thoughts is the quickest road to health.",
  "I am healthy, whole, and complete.",
  "I am at home in my body.",
  "I devote a portion of my time to helping others. It is good for my own health.",
  "I am greeted by love wherever I go.",
  "Wellness is the natural state of my body. I am in perfect health.",
  "I am pain free and totally in sync with life.",
  "I am very thankful for all the love in my life. I find it everywhere.",
  "I know that old, negative patterns no longer limit me. I let them go with ease.",
  "In the infinity of life where I am, all is perfect, whole, and complete.",
  "I trust my intuition. I am willing to listen to that still, small voice within.",
  "I am willing to ask for help when I need it.",
  "I forgive myself for not being perfect.",
  "I honor who I am.",
  "I attract only healthy relationships. I am always treated well.",
  "I do not have to prove myself to anyone.",
  "I come from the loving space of my heart, and I know that love opens all doors.",
  "I am in harmony with nature.",
  "I welcome new ideas.",
  "Today, no person, place, or thing can irritate or annoy me. I choose to be at peace.",
  "I am safe in the Universe and All Life loves and supports me.",
  "I experience love wherever I go.",
  "I am willing to change.",
  "I drink lots of water to cleanse my body and mind.",
  "I choose to see clearly with the eyes of love.",
  "I cross all bridges with joy and ease.",
  "I release all drama from my life.",
  "Loving others is easy when I love and accept myself.",
  "I balance my life between work, rest, and play.",
  "I return to the basics of life: forgiveness, courage, gratitude, love, and humor.",
  "I am in charge, I now take my own power back.",
  "My body appreciates how I take care of it.",
  "I spend time with positive, energetic people.",
  "The more peaceful I am inside, the more peace I have to share with others.",
  "Today is a sacred gift from Life.",
  "I have the courage to live my dreams.",
  "I release all negative thoughts of the past and all worries about the future.",
  "I forgive everyone in my past for all perceived wrongs. I release them with love.",
  "I only speak positively about those in my world. Negativity has no part in my life.",
  "We are all eternal spirit.",
  "I act as if I already have what I want—it’s an excellent way to attract happiness in my life.",
  "I enjoy the foods that are best for my body.",
  "My life gets better all the time.",
  "It is safe for me to speak up for myself.",
  "I live in the paradise of my own creation.",
  "Perfect health is my Divine right, and I claim it now.",
  "I release all criticism.",
  "I am on an ever-changing journey.",
  "I am grateful for my healthy body. I love life.",
  "Love flows through my body, healing all dis-ease.",
  "My income is constantly increasing.",
  "My healing is already in process.",
  "There is always more to learn.",
  "I now live in limitless love, light, and joy.",
  "I become more lovable every day.",
  "It is now safe for me to release all of my childhood traumas and move into love.",
  "I deserve all that is good.",
  "I am constantly discovering new ways to improve my health.",
  "Love is all there is!",
  "My life gets more fabulous every day.",
  "Today I am at peace.",
  "Loving others is easy when I love and accept myself.",
  "I have the perfect living space.",
  "I have compassion for all.",
  "I trust the Universe to help me see the good in everything and in everyone.",
  "I love my family members just as they are. I do not try to change anyone.",
  "There is plenty for everyone, and we bless and prosper each other.",
  "I love and approve of myself.",
  "Life is good, and so it is!"
]

let $imageArrays = [
  $animals,
  $mythicalCreatures,
  $vegetables,
  $bodyParts
]

let $inspiration = [
  'keep-going.gif',
  'worm.gif'
]
